spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Z4z5nNVsr/niF/CAvdZ4W/0KhwmENBW6EjZp808oJVinAWw9YrzpGmtZFU5K2GTHiyzy9RD9W6CioSCb+9EJDcopW0D2jdu2DXE4kDdFMA0=)
    username: ENC(HfwR05w1E/RITtuOu9w04w==)
    password: ENC(LJz0MQqtLrZhbORaBA0Mdg==)
  data:
    mongodb:
      uri: ENC(2TFSKUX5qxvJmH/3Mp4GVd28hTZr132l0dMzBmhqV7/VpcCTlcmNs8t2IgZR4U3FnzreQ2rGpuc7AABGoSJN+H9I72ZGLwGporjrOD+rS2lWJXoqJ1eE7Q==)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

openvidu:
  url: ENC(dHcH9uvYd42Efm/FQf80vH9Q/1a6pRNBZX4YRNISN+t15bmSVSWCGA==)
  secret: ENC(ETKG8ZovYz+lEMiK+WFfilJ9+JrZK5NO)