spring:
  application:
    name: igeolu

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      dev:
        - dev
    include:
      - key

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html