spring:
  application:
    name: igeolu

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      dev:
        - dev
    include:
      - key

  servlet:
    multipart:
      max-file-size: 9000MB
      max-request-size: 9000MB

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

file:
  upload-dir: ${user.home}/igeolu-file
  base-url: http://localhost:8080/files

