spring:
  application:
    name: igeolu

  profiles:
    group:
      local:
        - local
      prod:
        - prod
      dev:
        - dev
    include:
      - key

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

